spring:
  application:
    name: lecture02
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  security:
    oauth2:
      client:
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: login
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth

        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: read:user
            redirect-uri: http://localhost:8080/login/oauth2/code/github
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email
            redirect-uri: http://localhost:8080/login/oauth2/code/google


security:
  jwt:
    issuer: news-api
    expiration: 3600000

welcome:
  app-message: Welcome from application properties

logging:
  level:
    sql: debug
    org.springframework.security: DEBUG
    liquibase: debug

#management:
#  tracing:
#    sampling:
#      probability: 1.0  # Send 100% of requests to Jaeger for testing
#    otlp:
#      metrics:
#        export:
#          enabled: false
#      tracing:
#        endpoint: "http://localhost:4318/v1/traces"
#  endpoints:
#    web:
#      exposure:
#        include: health,info,prometheus
#  prometheus:
#    metrics:
#      export:
#        enabled: false